### ISSUE TITLE
It's unnecessary to use 2 functions.

### ISSUE THREAD

**Issue by akidan** [itochow/exercise_for_JS#1]
https://github.com/itochow/exercise_for_JS/blob/3e43f2dafe1dcc3fef038328e0dd94a8298fe56d/questions.txt#L12-L16

`function show() {
document.getElementById("demo").innerHTML=person.firstName + " " + person.lastName;
}`

It is easy to understand and save cost.

**Comment by itochow** [comment]
thank you so much~!
